### ISSUE TITLE
Support older Python versions?

### ISSUE THREAD

**Issue by james-smith-za** [coderlevelup/turtle-translated#6]
It looks like (based on some not-terribly-difficult detective work) this was either lifted from Python 3.1 or the `turtle` module hasn't changed at all since then, which also wouldn't surprise me.

Do you think it's worth making an effort to support Python 2.X?

**Comment by campey** [comment]
I don't actually know the effort to support that, but I would say usually learners will have a fresh install of python and no deps, so I'm not seeing many use cases where we will need 2.X unless there is a popular OS/distro that comes with 2.X that they would have by default.

**Comment by james-smith-za** [comment]
Fair point.
