### ISSUE TITLE
HacktoberFest2022

### ISSUE THREAD

**Issue by NileshArnaiya** [coderlevelup/turtle-translated#9]
Checklist:

- [ ]  I have read [Coderlevelup's contribution guidelines](https://github.com/coderlevelup/turtle-translated/#contributing).
- [ ]  I have created an issue describing what I'd like to change. 

Before Making a pull request:- 

- [ ]  My pull request has a descriptive title (not a vague title like Update index.md)
- [ ]  My pull request targets the main branch of turtle-translated.
- [ ]  I have tested these changes either locally on my machine, or GitPod.

@campey This could be the checklist template for anyone contributing and to participate in HacktoberFest I'd need to create Labels like '**Good First Issue**', **"Hacktoberfest-participant**' etc for others to find this repo on github. 
You can also list down your tasks and assign to different hacktoberfest participants and then I shall certainly market this to my open source community friends to contribute to the project.

**Comment by campey** [comment]
Thanks @NileshArnaiya, we have missed hacktoberfest for this year (I have been away from my github, apologies), but I think it is still a brilliant idea and we can use your suggestions next year to get more contribs, we would likely be more ready by then to accept contribs more easily.
